"""Built-in time comparison templates (spec M-05 / 4.5).

Windows are computed here, in Python, never generated by the LLM: hand-written
window functions are a high-error-rate path and the same question must always
produce the same range.
"""

from calendar import monthrange
from datetime import date, timedelta

from app.compiler.errors import UnsupportedComparisonError
from app.intent.schema import ComparisonKind, TimeRange

_LABELS = {
    ComparisonKind.MOM: "环比",
    ComparisonKind.YOY: "同比",
    ComparisonKind.WOW: "周环比",
    ComparisonKind.QOQ: "季环比",
    ComparisonKind.YTD: "年初至今同比",
    ComparisonKind.MTD: "月初至今环比",
    ComparisonKind.QTD: "季初至今环比",
    ComparisonKind.PREVIOUS_PERIOD: "上一周期",
}


def _shift_months(value: date, months: int) -> date:
    """Shift a date by whole months, clamping to the target month's length."""
    total = value.year * 12 + (value.month - 1) + months
    year, month = divmod(total, 12)
    month += 1
    day = min(value.day, monthrange(year, month)[1])
    return date(year, month, day)


def _shift_years(value: date, years: int) -> date:
    return _shift_months(value, years * 12)


def comparison_range(current: TimeRange, comparison: ComparisonKind) -> TimeRange:
    """Return the baseline window for a comparison against `current`."""
    if comparison == ComparisonKind.NONE:
        raise UnsupportedComparisonError("comparison", "无对比方式时不应请求对比区间")

    if comparison == ComparisonKind.MOM:
        start = _shift_months(current.start, -1)
        end = _shift_months(current.end, -1)
    elif comparison in (ComparisonKind.YOY, ComparisonKind.YTD):
        start = _shift_years(current.start, -1)
        end = _shift_years(current.end, -1)
    elif comparison == ComparisonKind.WOW:
        start = current.start - timedelta(days=7)
        end = current.end - timedelta(days=7)
    elif comparison == ComparisonKind.QOQ:
        start = _shift_months(current.start, -3)
        end = _shift_months(current.end, -3)
    elif comparison == ComparisonKind.MTD:
        start = _shift_months(current.start, -1)
        end = _shift_months(current.end, -1)
    elif comparison == ComparisonKind.QTD:
        start = _shift_months(current.start, -3)
        end = _shift_months(current.end, -3)
    else:  # PREVIOUS_PERIOD: immediately preceding window of equal length.
        span = current.end - current.start
        end = current.start - timedelta(days=1)
        start = end - span

    return TimeRange(
        start=start,
        end=end,
        grain=current.grain,
        expression=f"{_LABELS[comparison]}对比期",
    )


def comparison_label(comparison: ComparisonKind) -> str:
    if comparison == ComparisonKind.NONE:
        return ""
    return _LABELS[comparison]