livy.server.host = 0.0.0.0
livy.server.port = 8998
livy.spark.master = spark://spark-master:7077
livy.file.local-dir-whitelist = /opt/meridian/jobs
livy.server.recovery.mode = recovery
livy.server.recovery.state-store = filesystem
livy.server.recovery.state-store-filesystem.path = /opt/livy/run/recovery
livy.server.session.timeout = 30m
