coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
discovery.uri=http://trino-coordinator:8080
query.max-memory=2GB
query.max-memory-per-node=768MB
query.max-execution-time=10m
query.max-run-time=15m
query.max-scan-physical-bytes=20GB
resource-groups.configuration-manager=file
